name: $(Build.DefinitionName)+$(Build.BuildId)+$(Rev:r)

# resources:
#   pipelines:
#     - pipeline: serverstarter
#       branch: master
#       project: StoneIndustries
#       source: ServerStarter
#       trigger:
#         stages:
#           - dev
#     - pipeline: kubejs_alchemistry
#       branch: master
#       project: StoneIndustries
#       source: KubeJS-Alchemistry
#       trigger:
#         stages:
#           - dev

parameters:
  - name: MinecraftVersion
    displayName: Minecraft Version
    type: string
    default: 1.16.5
  - name: ModpackName
    displayName: Modpack Name
    type: string
    default: Stone Industries
  - name: ModpackAuthor
    displayName: Modpack Author
    type: string
    default: Stone Industries Team
  - name: ModpackVersion
    displayName: Modpack Version
    type: string
    default: 0.0.2
  - name: ForgeVersion
    displayName: Forge Version
    type: string
    default: 36.1.2
  - name: ReleaseNotes
    displayName: Release Notes
    type: string
    default: ''
  - name: GitHubOrg
    displayName: GitHub Organization
    type: string
    default: 'Stone-Industries'
  - name: GitHubRepo
    displayName: GitHub Repo
    type: string
    default: 'Minecraft'
  - name: PterodactylAddress
    displayName: Pterodactyl Address
    type: string
    default: 'https://pterodactyl.sandboxservers.games'
  - name: CreatePrerelease
    displayName: Create Prerelease
    type: boolean
    default: false

trigger: 
  branches:
    include:
      - master
      - prerelease/*
  tags:
    include:
      - release/*

pool:
  name: Sandbox Servers Agents

stages:
  - template: pipeline-templates/stages/build-stage.yml
    parameters:
        MinecraftVersion: ${{ parameters.MinecraftVersion }}
        ModpackVersion: ${{ parameters.ModpackVersion }}
        ForgeVersion: ${{ parameters.ForgeVersion }}
        ModpackName: ${{ parameters.ModpackName }}
        ModpackAuthor: ${{ parameters.ModpackAuthor }}
        SourcesDirectory: $(Build.SourcesDirectory)
        BinariesDirectory: $(Build.BinariesDirectory)
        ArtifactDirectory: $(Build.ArtifactStagingDirectory)

  - stage: dev
    displayName: "Dev"
    variables:
      - group: StoneIndustries-Git
      - group: StoneIndustries-Modpack-Dev
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    jobs:
      - template: pipeline-templates/jobs/deploy-to-server-lower-env.yml
        parameters:
          ServerID: $(ServerID)
          PterodactylAddress: ${{ parameters.PterodactylAddress }}
          PipelineWorkspace: $(Pipeline.Workspace)

      - template: pipeline-templates/jobs/push-to-github.yml
        parameters:
          GitHubOrg: ${{ parameters.GitHubOrg }}
          GitHubRepo: ${{ parameters.GitHubRepo }}
          SourcesDirectory: $(Build.SourcesDirectory)
          TempDirectory: $(Agent.TempDirectory)

      - template: pipeline-templates/jobs/create-github-prerelease.yml
        parameters:
          GitHubOrg: ${{ parameters.GitHubOrg }}
          GitHubRepo: ${{ parameters.GitHubRepo }}
          ModpackVersion: ${{ parameters.ModpackVersion }}
          CreatePrerelease: ${{ parameters.CreatePrerelease }}
          ReleaseNotes: ${{ parameters.ReleaseNotes }}

  - stage: staging
    variables:  
      - group: StoneIndustries-Git
      - group: StoneIndustries-Modpack-Staging
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/prerelease/'))
    displayName: "Staging"
    jobs:
      - template: pipeline-templates/jobs/deploy-to-server-lower-env.yml
        parameters:
          ServerID: $(ServerID)
          PterodactylAddress: ${{ parameters.PterodactylAddress }}
          PipelineWorkspace: $(Pipeline.Workspace)