name: $(Build.DefinitionName)-$(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:.r)

# resources:
#   pipelines:
#     - pipeline: serverstarter
#       branch: master
#       project: StoneIndustries
#       source: ServerStarter
#       trigger:
#         stages:
#           - dev

parameters:
  - name: ModpackVersion
    displayName: Modpack Version
    type: string
    default: 0.0.3
  - name: PushToGithub
    displayName: Push To Github
    type: boolean
    default: true
  - name: CreatePrerelease
    displayName: Create Prerelease
    type: boolean
    default: false
  - name: CreateRelease
    displayName: Create Release
    type: boolean
    default: false
  - name: isProdDeployment
    displayName: Deploy To Prod
    type: boolean
    default: false

variables:
 - group: StoneIndustries-Modpack
 - group: StoneIndustries-Git

trigger: 
  branches:
    include:
      - master
      - prerelease/*
      - release/*
  tags:
    include:
      - prerelease/*
      - release/*

pool:
  name: Sandbox Servers Agents

stages:
  - template: pipeline-templates/pipelines/modpack-pipeline.yml
    parameters:
      MinecraftVersion: $(MinecraftVersion)
      ModpackVersion: ${{ parameters.ModpackVersion }}
      ForgeVersion: $(ForgeVersion)
      ModpackName: $(ModpackName)
      ModpackAuthor: $(ModpackAuthor)
      PterodactylAddress: $(PterodactylAddress)
      GitHubOrg: $(GitHubOrg)
      GitHubRepo: $(GitHubRepo)
      CreatePrerelease: ${{ parameters.CreatePrerelease }}
      CreateRelease: ${{ parameters.CreateRelease }}
      isProdDeployment: ${{ parameters.isProdDeployment }}
      PushToGithub: ${{ parameters.PushToGithub }}