parameters:
  - name: MinecraftVersion
    default: ''
  - name: ModpackName
    default: ''
  - name: ModpackAuthor
    default: ''
  - name: ModpackVersion
    default: ''
  - name: ForgeVersion
    default: ''
  - name: GitHubOrg
    default: ''
  - name: GitHubRepo
    default: ''
  - name: CommitMessage
    default: ''
  - name: PterodactylAddress
    default: ''
  - name: PushToGithub
    default: false
  - name: CreatePrerelease
    default: false
  - name: CreateRelease
    default: false
  - name: isProdDeployment
    default: false

stages:
  - template: ../stages/build-client-stage.yml
    parameters:
      MinecraftVersion: ${{ parameters.MinecraftVersion }}
      ModpackVersion: ${{ parameters.ModpackVersion }}
      ForgeVersion: ${{ parameters.ForgeVersion }}
      ModpackName: ${{ parameters.ModpackName }}
      ModpackAuthor: ${{ parameters.ModpackAuthor }}
  
  - template: ../stages/build-server-stage.yml
    parameters:
      MinecraftVersion: ${{ parameters.MinecraftVersion }}
      ModpackVersion: ${{ parameters.ModpackVersion }}
      ForgeVersion: ${{ parameters.ForgeVersion }}
      ModpackName: ${{ parameters.ModpackName }}
      ModpackAuthor: ${{ parameters.ModpackAuthor }}
      GitHubOrg: ${{ parameters.GitHubOrg }}
      GitHubRepo: ${{ parameters.GitHubRepo }}
      CommitMessage: ${{ parameters.CommitMessage }}
      PushToGithub: ${{ parameters.PushToGithub }}

  - template: ../stages/dev-stage.yml
    parameters:
      ModpackVersion: ${{ parameters.ModpackVersion }}
      ModpackName: ${{ parameters.ModpackName }}
      ServerID: $(DevServerID)
      PterodactylAddress: ${{ parameters.PterodactylAddress }}
      GitHubOrg: ${{ parameters.GitHubOrg }}
      GitHubRepo: ${{ parameters.GitHubRepo }}
      PushToGithub: ${{ parameters.PushToGithub }}
      CreatePrerelease: ${{ parameters.CreatePrerelease }}

  - template: ../stages/staging-stage.yml
    parameters:
      ModpackVersion: ${{ parameters.ModpackVersion }}
      ModpackName: ${{ parameters.ModpackName }}
      ServerID: $(StagingServerID)
      PterodactylAddress: ${{ parameters.PterodactylAddress }}
      GitHubOrg: ${{ parameters.GitHubOrg }}
      GitHubRepo: ${{ parameters.GitHubRepo }}
      PushToGithub: ${{ parameters.PushToGithub }}
      CreateRelease: ${{ parameters.CreateRelease }}

  - template: ../stages/prod-stage.yml
    parameters:
      ServerID: $(ProdServerID)
      PterodactylAddress: ${{ parameters.PterodactylAddress }}
      isProdDeployment: ${{ parameters.isProdDeployment }}