parameters:
  - name: ModpackVersion
    default: ''
  - name: ServerID
    default: ''
  - name: PterodactylAddress
    default: ''
  - name: PipelineWorkspace
    default: ''
  - name: GitHubOrg
    default: ''
  - name: GitHubRepo
    default: ''
  - name: CreatePrerelease
    default:
  - name: ReleaseNotes
    default:
  - name: SourcesDirectory
    default:
  - name: TempDirectory
    default:
stages:
  - stage: dev
    displayName: "Dev"
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    jobs:
      - template: ../jobs/deploy-to-server-lower-env.yml
        parameters:
          ServerID: ${{ parameters.ServerID }}
          PterodactylAddress: ${{ parameters.PterodactylAddress }}
          PipelineWorkspace: ${{ parameters.PipelineWorkspace }}

      - template: ../jobs/push-to-github.yml
        parameters:
          GitHubOrg: ${{ parameters.GitHubOrg }}
          GitHubRepo: ${{ parameters.GitHubRepo }}
          SourcesDirectory: ${{ parameters.SourcesDirectory }}
          TempDirectory: ${{ parameters.TempDirectory }}

      - template: ../jobs/create-github-release.yml
        parameters:
          GitHubOrg: ${{ parameters.GitHubOrg }}
          GitHubRepo: ${{ parameters.GitHubRepo }}
          ModpackVersion: ${{ parameters.ModpackVersion }}
          CreatePrerelease: ${{ parameters.CreatePrerelease }}
          ReleaseNotes: ${{ parameters.ReleaseNotes }}