parameters:
  - name: ModpackVersion
    default: ''
  - name: ModpackName
    default: ''
  - name: GitHubOrg
    default: ''
  - name: GitHubRepo
    default: ''
  - name: CreatePrerelease
    default: false
  - name: CreateRelease
    default: false
  - name: ReleaseNotes
    default: ''
jobs:
  - deployment: createrelease
    dependsOn: performpr
    condition: |
      or(
        and(
          succeeded(), 
          eq(
            '${{ parameters.CreatePrerelease }}', true
          )
        ),
        and(
          succeeded(), 
          eq(
            '${{ parameters.CreateRelease }}', true
          )
        )
      )
    environment: StoneIndustries-Dev
    ${{ if eq('${{ parameters.CreatePrerelease }}', true) }}:
      displayName: "Create GitHub PreRelease"
    ${{ if eq('${{ parameters.CreateRelease }}', true) }}:
      displayName: "Create GitHub Release"
    workspace:
        clean: all
    strategy:
        runOnce:
          deploy:
              steps:
                - task: GitHubRelease@1
                  displayName: "Create Github Prerelease"
                  name: githubprerelease
                  condition: and(succeeded(), eq(${{ parameters.CreatePrerelease }}, 'true'))
                  inputs:
                    gitHubConnection: 'github.com_Cadacious'
                    repositoryName: '$(Build.Repository.Name)'
                    action: 'create'
                    target: '$(Build.SourceVersion)'
                    tagSource: 'userSpecifiedTag'
                    tag: '${{ parameters.ModpackVersion }}-preview'
                    title: '${{ parameters.ModpackName }} (${{ parameters.ModpackVersion }})'
                    releaseNotesFilePath: 'change-logs/${{ parameters.ModpackVersion }}'
                    isPreRelease: true
                    addChangeLog: false
                - task: GitHubRelease@1
                  displayName: "Create Github Release"
                  name: githubrelease
                  condition: and(succeeded(), eq(${{ parameters.CreateRelease }}, 'true'))
                  inputs:
                    gitHubConnection: 'github.com_Cadacious'
                    repositoryName: '$(Build.Repository.Name)'
                    action: 'create'
                    target: '$(Build.SourceVersion)'
                    tagSource: 'userSpecifiedTag'
                    tag: '${{ parameters.ModpackVersion }}'
                    title: '${{ parameters.ModpackName }} (${{ parameters.ModpackVersion }})'
                    releaseNotesFilePath: 'change-logs/${{ parameters.ModpackVersion }}'
                    isPreRelease: false
                    changeLogCompareToRelease: 'lastFullRelease'
                    changeLogType: 'commitBased'