parameters:
  - name: ModpackVersion
    default: ''
  - name: ModpackName
    default: ''
  - name: GitHubOrg
    default: ''
  - name: GitHubRepo
    default: ''
  - name: GitHubSourceBranch
    default: ''
  - name: CreatePrerelease
    default: false
  - name: CreateRelease
    default: false
  - name: ReleaseNotes
    default: ''
jobs:
  - deployment: createrelease
    dependsOn: performpr
    condition: |
      or(
        and(
          succeeded(), 
          eq(
            '${{ parameters.CreatePrerelease }}', true
          )
        ),
        and(
          succeeded(), 
          eq(
            '${{ parameters.CreateRelease }}', true
          )
        )
      )
    environment: StoneIndustries-${{ Variables.System.StageName }}
    workspace:
        clean: all
    strategy:
        runOnce:
          deploy:
              steps:
                - checkout: self
                - task: GitHubRelease@1
                  displayName: "Create Github Prerelease"
                  name: githubprerelease
                  condition: and(succeeded(), eq(${{ parameters.CreatePrerelease }}, 'true'))
                  inputs:
                    gitHubConnection: 'github.com_Cadacious'
                    repositoryName: 'Stone-Industries/Minecraft'
                    action: 'create'
                    target: '${{ parameters.ModpackVersion }}'
                    tagSource: 'userSpecifiedTag'
                    tag: 'v${{ parameters.ModpackVersion }}'
                    title: '${{ parameters.ModpackName }} (${{ parameters.ModpackVersion }})'
                    releaseNotesFilePath: 'change-logs/${{ parameters.ModpackVersion }}.md'
                    assets: |
                      $(Pipeline.Workspace)/server-modpack-download/*
                      $(Pipeline.Workspace)/client-modpack-download/*
                    isPreRelease: true
                    addChangeLog: false
                - task: GitHubRelease@1
                  displayName: "Create Github Release"
                  name: githubrelease
                  condition: and(succeeded(), eq(${{ parameters.CreateRelease }}, 'true'))
                  inputs:
                    gitHubConnection: 'github.com_Cadacious'
                    repositoryName: 'Stone-Industries/Minecraft'
                    action: 'create'
                    target: '${{ parameters.ModpackVersion }}'
                    tagSource: 'userSpecifiedTag'
                    tag: 'v${{ parameters.ModpackVersion }}'
                    title: '${{ parameters.ModpackName }} (${{ parameters.ModpackVersion }})'
                    releaseNotesFilePath: 'change-logs/${{ parameters.ModpackVersion }}.md'
                    assets: |
                      $(Pipeline.Workspace)/server-modpack-download/*
                      $(Pipeline.Workspace)/client-modpack-download/*
                    isPreRelease: false
                    changeLogCompareToRelease: 'lastFullRelease'
                    changeLogType: 'commitBased'