parameters:
  - name: GitHubOrg
    default: ''
  - name: GitHubRepo
    default: ''
  - name: ModpackVersion
    default: ''
  - name: CreatePrerelease
    default: ''
  - name: ReleaseNotes
    default: ''
jobs:
  - deployment:
    condition: and(succeeded(), eq('${{ parameters.CreatePrerelease }}', true))
    environment: StoneIndustries-Dev
    displayName: "Create GitHub PreRelease"
    workspace:
        clean: all
    strategy:
        runOnce:
          deploy:
              steps:
              - powershell: |
                  $Token = $env:PERSONALACCESSTOKEN
                  
                  $Body = [Ordered]@{
                  "tag_name"="${{ parameters.ModpackVersion }}"; 
                  "name"="Stone Industries (${{ parameters.ModpackVersion }}"; 
                  "body"="${{ parameters.ReleaseNotes }}"; 
                  "prerelease"=$true;
                  "draft"=$true;
                  } | convertto-json
                  
                  Invoke-RestMethod -Method Post -uri https://api.github.com/repos/${{ parameters.GitHubOrg }}/${{ parameters.GitHubRepo }}/releases -Headers @{"Authorization"="token $Token"; "accept"="application/vnd.github.v3+jso"} -body "$body"
                displayName: "Create Prerelease via REST API"
                env:
                    PersonalAccessToken: $(Git-Token)