parameters:
  - name: GitHubOrg
    default: ''
  - name: GitHubRepo
    default: ''
  - name: GitHubSourceBranch
    default: ''
  - name: GitHubDestinationBranch
    default: ''
  - name: ModpackVersion
    default: ''
jobs:
  - deployment: performpr
    dependsOn: deployserver
    environment: StoneIndustries-Dev
    displayName: "Perform GitHub Pull Request"
    workspace:
        clean: all
    strategy:
        runOnce:
          deploy:
              steps:
              - powershell: |
                  $Token = $env:PERSONALACCESSTOKEN
                  
                  $Body = [Ordered]@{
                  "title"="Stone Industries (${{ parameters.ModpackVersion }})"; 
                  "head"="${{ parameters.GitHubSourceBranch }}";
                  "base"="${{ parameters.GitHubDestinationBranch }}";
                  "body"="Opening Pull Request to ${{ parameters.GitHubDestinationBranch }} branch after successful deployment to ${{ parameters.GitHubDestinationBranch }} server.";
                  "maintainer_can_modify"=$true;
                  "draft"=$false;
                  } | convertto-json

                  $Headers = @{"Authorization"="token $Token"; "accept"="application/vnd.github.v3+json"}
                  $URI = "https://api.github.com/repos/${{ parameters.GitHubOrg }}/${{ parameters.GitHubRepo }}/pulls"

                  Invoke-RestMethod -Method Post -uri $URI -Headers $Headers -body "$body" | Tee-Object -Variable REST
                  Write-Host "##vso[task.setvariable variable=prnumber]$($REST.number)"
                  Write-Host "##vso[task.setvariable variable=prsha]$($REST.head.sha)"
                displayName: "Create Pull Request via REST API"
                env:
                    PersonalAccessToken: $(Git-Token)
              - powershell: |
                  $Token = $env:PERSONALACCESSTOKEN

                  $Body = [Ordered]@{
                  "commit_title"="Completing PR";
                  "commit_message"="Completing PR to ${{ parameters.GitHubDestinationBranch }} branch via Azure Pipelines"
                  "sha"="$env:PRSHA"
                  "merge_method"="squash"
                  } | convertto-json

                  $Headers = @{"Authorization"="token $Token"; "accept"="application/vnd.github.v3+json"}
                  $URI = "https://api.github.com/repos/${{ parameters.GitHubOrg }}/${{ parameters.GitHubRepo }}/pulls/$env:PRNUMBER/merge"

                  Invoke-RestMethod -Method Post -uri $URI -Headers $Headers -body "$body" | Tee-Object -Variable REST
                displayName: "Merge Pull Request via REST API"
                env:
                    PersonalAccessToken: $(Git-Token)