parameters:
  - name: GitHubOrg
    default: ''
  - name: GitHubRepo
    default: ''
  - name: PushToGithub
    default: true
jobs:
  - deployment: pushtogit
    condition: |
      and(
        succeeded(), 
        and(
          ne(
            variables['Build.Reason'], 'PullRequest'
          ),
          eq(
            ${{ parameters.PushToGithub }}, 'true'
          )
        )
      )
    dependsOn: buildandpackage
    environment: StoneIndustries-${{ Variables.System.StageName }}
    displayName: "Push to GitHub"
    workspace:
      clean: all
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - powershell: |
              $env:GIT_REDIRECT_STDERR = '2>&1'
              $RepoURL = "https://Cadacious:$env:PERSONALACCESSTOKEN@github.com/${{ parameters.GitHubOrg }}/${{ parameters.GitHubRepo }}"

              Set-Location $(Agent.TempDirectory)
              Remove-Item $(Agent.TempDirectory)\${{ parameters.GitHubRepo }} -recurse -force -erroraction silentlycontinue
              git config --global user.name "Azure-Pipelines"
              git config --global user.email "Azure-Pipelines@SandboxServers.games"
              
              git clone --branch dev $RepoURL

              Set-Location $(Agent.TempDirectory)\${{ parameters.GitHubRepo }}

              Remove-Item $(Agent.TempDirectory)\${{ parameters.GitHubRepo }}\* -Recurse

              Copy-Item -Path $(Build.SourcesDirectory)\* -Destination $(Agent.TempDirectory)\${{ parameters.GitHubRepo }}\ -recurse

              git add --all
              git commit -m "Merging to GitHub Dev branch from Azure DevOps after successful build"
              git push origin dev

              $env:PERSONALACCESSTOKEN | out-file $(Agent.TempDirectory)\token.txt
            displayName: 
            env:
              PersonalAccessToken: $(Git-Token)